### ISSUE TITLE
How to retain materials on CSG applied mesh?

### ISSUE THREAD

**Issue by sushant380** [samalexander/three-csg-ts#1]
Consider if both the meshes have their own materials in place before subtraction, how do we retain the original material after subtraction?

**Comment by samalexander** [comment]
@sushant380 this is beyond the scope of this library.

If you check the README, you will see that material is assigned to the resulting mesh manually by copying from meshA. This gives you fine-grained control over which properties are carried over.
```
// Get the resulting mesh from the result bsp
const meshResult = CSG.toMesh(bspResult, meshA.matrix);

// Set the results material to the material of the first cube.
meshResult.material = meshA.material;
```
