### ISSUE TITLE
Support for multiple materials

### ISSUE THREAD

**Issue by xawill** [samalexander/three-csg-ts#12]
I am working with a BufferGeometry containing multiple (3) groups, each group being assigned to a different Material in the corresponding Mesh both the BufferGeometry and the Materials are assigned to.

The issue is that your (super useful) library seems to disregard the materialIndex of the Geometry created from the source BufferGeometry (via `Geometry.fromBufferGeometry`). It means that I cannot reapply the array of (3) Materials from my original Mesh to your outputted Mesh, as only the first Material in my array of Material will be applied to all the vertices of the outputted Geometry, as all their vertices gave the default materialIndex = 0.

Let me know if you see any possible fix. I guess from my (basic) understanding of your library that it might be a possibility to add a `materialIndex ` property to your `Vertex` object, in order to be able to reapply it before returning the outputted Mesh.

**Comment by samalexander** [comment]
@xawill are you able to provide us with a simple example of the issue you are facing via Stackblitz or similar? Then we'll take a look.

**Comment by xawill** [comment]
This is part of a huge commercial project, so making it "simple" would require some not negligible time investment. Are you sure you really need this ? If I am right with my hypothesis mentioned above (I haven't tested it yet) the fix is quite straight forward ; can I submit a PR myself instead so that you don't have to investigate the issue yourself (as I can directly test the fix with my codebase) ?

**Comment by samalexander** [comment]
Yes, please submit a PR 👍🏼
