### ISSUE TITLE
Matrix inverse behaviour changed with release 2.0.0

### ISSUE THREAD

**Issue by xawill** [samalexander/three-csg-ts#13]
You handled the Matrix4 getInverse deprecation in three r123 in 2.0.0 and this is great! However, the new addition with `toMatrix.invert()` (see below, for reference) doesn't keep the backward compatibility with the previous version.

Indeed, the new `toMatrix.invert()` call modifies the `toMatrix` matrix where the previous one didn't, as it was creating a copy (`inv = new Matrix4().getInverse(toMatrix)`).

So I suggest either you specify in the docs that the passed matrix will be affected (unlike before) or that you also create a Matrix4 copy in the line referenced below.

Thank you!

PS: Let me know if you want me to create a PR for this.

https://github.com/Jiro-Digital/three-csg-ts/blob/d04eb4bb2efa01a26353d50ea50a678c4f2f2feb/src/index.ts#L88

**Comment by samalexander** [comment]
This is fixed in v2.0.1

**Comment by xawill** [comment]
That was fast ! Thank you
