### ISSUE TITLE
Support latest version of ThreeJS (0.127)

### ISSUE THREAD

**Issue by JeffreyArts** [samalexander/three-csg-ts#20]
**Is your feature request related to a problem? Please describe.**
I use one of the latest versions of ThreeJS and three-csg-ts does not support that.

**Describe the solution you'd like**
I want this module work without limiting my ThreeJS to a certain version.

**Describe alternatives you've considered**
Not using the latest ThreeJS version

**Comment by JeffreyArts** [comment]
https://github.com/JeffreyArts/three-csg-ts/tree/patch-1

**Comment by darkwave** [comment]
Am I wrong or `Face3` and `Geometry` are not part of Three.js anymore in `0.127.0`? :thinking:

**Comment by lehne** [comment]
Geometry has been removed from Three.js: https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401
