### ISSUE TITLE
Undefined position when I subtract two boxes after the update to 3.1.4

### ISSUE THREAD

**Issue by Houssk** [samalexander/three-csg-ts#31]
- Undefined position when I subtract two boxes after the update to 3.1.4

`    const meshA = new Mesh(new THREE.BoxGeometry(1,1,1), new THREE.MeshNormalMaterial());
    const meshB = new THREE.Mesh(new THREE.BoxGeometry(1,1,1));
    meshB.position.add(new THREE.Vector3(0.5, 0.5, 0.5));
    meshA.updateMatrix();
    meshB.updateMatrix();
    const meshResult = CSG.subtract(meshA, meshB);`

**Screenshots**
![image](https://user-images.githubusercontent.com/8850783/123293480-50683180-d514-11eb-8140-d147995dc830.png)

any idea ?

**Comment by samalexander** [comment]
Your steps to reproduce appear to work fine for me:

https://stackblitz.com/edit/three-csg-ts-nrsjqm

Are you able to supply a Stackblitz or similar that demonstrates the issue?

**Comment by Houssk** [comment]
Thanks for the answer, it was a problem with threejs (ts version), the example works well,
 I tried to do a subtraction between two stl objects and I got the following error.
![image](https://user-images.githubusercontent.com/8850783/123423196-87dfe800-d5bf-11eb-8c63-f91204dc6e82.png)
![image](https://user-images.githubusercontent.com/8850783/123423250-975f3100-d5bf-11eb-9fdc-90c5b3b21962.png)

**Comment by Houssk** [comment]
Hey @samalexander,

I got it, I had to add some uv-attributes to my buffergeometry ...

Thanks ;)
