### ISSUE TITLE
Extrude geometry union torus deletes torus.

### ISSUE THREAD

**Issue by awongh** [samalexander/three-csg-ts#38]
**Describe the bug**
Union of extrude geometry and torus deletes the torus and removes faces from the extruded shape. 

**To Reproduce**
```js
const length = 1,
  width = 1;
const shape = new THREE.Shape();
shape.moveTo(0, 0);
shape.lineTo(0, width);
shape.lineTo(length, width);
shape.lineTo(length, 0);
shape.lineTo(0, 0);

const extrudeSettings = {
  depth: 1,
  bevelEnabled: false
};

const extrudeGeometry = new THREE.ExtrudeGeometry(shape, extrudeSettings);
const extrudeMaterial = new THREE.MeshNormalMaterial();
const extrudeMesh = new THREE.Mesh(extrudeGeometry, extrudeMaterial);

const torusGeometry = new THREE.TorusGeometry(0.5, 0.3, 11, 10);
const torusMaterial = new THREE.MeshNormalMaterial();
const torusMesh = new THREE.Mesh(torusGeometry, torusMaterial);

const meshResult = CSG.union(torusMesh, extrudeMesh);
```
https://codesandbox.io/s/three-csg-extrude-error-torus-forked-ie7z5?file=/src/index.js:558-1381

**Expected behavior**
Unions both shapes together.
<img width="760" alt="ext-torus-working" src="https://user-images.githubusercontent.com/193142/129841193-10f5fc72-19a2-44ad-a1a2-2022c42b85be.png">
Should look like this.

**Screenshots**
<img width="890" alt="ext-torus-bug" src="https://user-images.githubusercontent.com/193142/129841215-03f5a461-fb8d-48f5-b741-4aaf144a00e3.png">
Face of the extrusion and the torus is deleted.

**Additional context**

The issue seems to be related to the version of the library: (in code sandbox you can select the library version number)
In 3.1.6, the torus is deleted and the face of the extrusion is deleted.
In 3.1.5 - 3.1.3 only the torus is deleted.
In 3.1.2 the error is: `Cannot read property 'vertices' of undefined`
In 3.1.1 and below works ok.

Union between a box and an extruded shape errors similarly:
https://codesandbox.io/s/three-csg-extrude-error-pwj8p?file=/src/index.js
In 3.1.6 and above a face of the extrusion is deleted.
In 3.1.5 and below the union works without errors.

Here is a working example for all versions based on the code example in the repo readme:
https://codesandbox.io/s/three-csg-working-exx-cx8fs?file=/src/index.js

I'm not particularly versed in threejs or 3d, but this is what I've observed.
thanks🙏

**Comment by samalexander** [comment]
Fixed in v3.1.8
