### ISSUE TITLE
Problem with Rotation

### ISSUE THREAD

**Issue by MichaelHilgers** [samalexander/three-csg-ts#43]
Hello,

i have a problem with substract, union an intersect when the parent Groups of a mesh are rotated.
The position of the meshs in World are not apply before doing the substract.

Please view my code Sample:

`private csgSample(){

var scene = this.baseScene.scene;

const camera = new THREE.PerspectiveCamera(
  75,
  window.innerWidth / window.innerHeight,
  0.1,
  1000
)
camera.position.x = 0.5
camera.position.y = 2
camera.position.z = 2.5
camera.up.set(0, 0, 1);

this.baseScene.camera = camera;
this.baseScene.controls = new OrbitControls(camera, this.baseScene.renderer.domElement);

  //create a cube and sphere and intersect them
  const cubeMesh = new THREE.Mesh(
    new THREE.BoxGeometry(2, 2, 2),
    new THREE.MeshPhongMaterial({ color: 0xff0000,
      opacity: 0.5,
      transparent:true, })
)
const sphereMesh = new THREE.Mesh(
    new THREE.SphereGeometry(1.45, 8, 8),
    new THREE.MeshPhongMaterial({ color: 0x0000ff ,
      opacity: 0.5,
      transparent:true,})
)

var g = new THREE.Group();
g.position.set(0.5, 0, 0.5);
g.rotation.x = 15;
cubeMesh.position.set(0, 0, 1);
g.add(cubeMesh);
scene.add(g)

sphereMesh.position.set(0, 0, 0)
scene.add(sphereMesh)

scene.updateMatrix();
scene.updateMatrixWorld(true);

var meshResult  = CSG.subtract( cubeMesh, sphereMesh);

meshResult.material = new THREE.MeshPhongMaterial({
    color: 0xff00ff
})
//g.add(meshResult);
meshResult.position.set(0, 0, -5)
scene.add(meshResult)

scene.updateMatrix();
scene.updateMatrixWorld(true);
}`

![image](https://user-images.githubusercontent.com/12812984/137258718-25e18612-f7ac-4829-a710-56229300fcba.png)

**Comment by samalexander** [comment]
Also reported in https://github.com/manthrax/THREE-CSGMesh/issues/14. Linking here for reference.
