### ISSUE TITLE
EdgesGeometry renders to many lines

### ISSUE THREAD

**Issue by SelfMade2001** [samalexander/three-csg-ts#50]
**Describe the bug**
I am generating an EdgesGeometry form a mesh that is created by  using `CSG.subtract(cube, cylinder);`. As you can see in the screenshot there appear lines even though EdgesGeometry should not render lines that are on a flat surface. This happens even if the thresholdAngle is set very high.

**Minimal reproduction of issue**
I am basically using this code:
```
            const geometry1 = new THREE.BoxGeometry(10, 10, 10);
            const material = new THREE.MeshStandardMaterial({
                color: 0x00ff00,
                polygonOffset: true,
                polygonOffsetFactor: 1,
                polygonOffsetUnits: 1,
            });
            const cube = new THREE.Mesh(geometry1, material);
            const geometry2 = new THREE.CylinderGeometry(4, 4, 20, 32);
            const cylinder = new THREE.Mesh(geometry2, material);
            let mesh = CSG.subtract(cube, cylinder);
            scene.add(mesh);

            let wireframe = new THREE.EdgesGeometry(mesh.geometry, 1); // using EdgesGeometry even though calling it wireframe
            let line = new THREE.LineSegments(wireframe);
            line.material.color.setHex(0x000000);
            scene.add(line);
```
This code is how I generated the screenshot

**Expected behavior**
I expect EdgesGeometry  to only render lines if they are between faces that have an angle greater than the thresholdAngle between them. That is how I understand the docs: https://threejs.org/docs/?q=edges#api/en/geometries/EdgesGeometry

**Screenshots**
![EdgesGeometryIssue](https://user-images.githubusercontent.com/68068047/169402037-65437a58-514a-48b0-9db2-b46fab24e8a8.jpg)

**Additional context**
I am not sure if this is a bug. Maybe you could see this as a feature request or just tell me what I am doing wrong. Thank you :)

**Comment by manthrax** [comment]
Can you try using https://threejs.org/docs/#examples/en/utils/BufferGeometryUtils.mergeVertices on your model with a small tolerance, and see if that helps?

The way the algorithm works is on a per triangle basis, so the connectivity information is lost in the process. Merging the vertices may restore some of it.

**Comment by SelfMade2001** [comment]
Thank you for your help. I tried your solution, but sadly it did not work. It did not change a thing with a small tolerance and with a large tolerance the hole in the middle gets ugly while the lines I want to remove stay the same.
