### ISSUE TITLE
Conversion indexing error for colors at CSG.fromGeometry

### ISSUE THREAD

**Issue by liu-hanli** [samalexander/three-csg-ts#56]
**Describe the bug**
In `CSG.fromGeometry`, when the color attributes are assigned to vertices of polygons, an incorrect index is used.

**Expected behavior**
In 'CSG.ts', lines 67-69, replace `vt` by `vp`.

**Screenshots**
![image](https://user-images.githubusercontent.com/79277929/213665548-b9c32f3e-269f-4904-b027-ee939d03f27a.png) ![image](https://user-images.githubusercontent.com/79277929/213665239-a7942e14-1f4e-44c1-bce0-bee70c99e237.png)

**Comment by samalexander** [comment]
@liu-hanli are you able to create a PR with the fix?

**Comment by liu-hanli** [comment]
> @liu-hanli are you able to create a PR with the fix?

Created

**Comment by samalexander** [comment]
Released in [v3.1.13](https://github.com/samalexander/three-csg-ts/releases/tag/v3.1.13). Thanks for your contribution!
