### ISSUE TITLE
Substraction with 3D Text 3RF

### ISSUE THREAD

**Issue by marcofiletto** [samalexander/three-csg-ts#60]
**Describe the bug**
_TypeError: Cannot read properties of undefined (reading 'count')_
I am getting an error when trying to subtract <3DText> element from Drei. It seems that the type of 3DText is invalid (is not _textGeometry_).

**Minimal reproduction of issue**
Put <3DText> inside <Substraction> and see the console.

**Additional context**
 I have used <textGeometry> from three js (I know it's deprecated but it's the only way I found) but for some reason the performance is very slow.

**Comment by samalexander** [comment]
@marcofiletto please could you provide a worked example of this issue via [Stackblitz](https://stackblitz.com/) or similar?

**Comment by marcofiletto** [comment]
Hey! I have used simple CSG (without ts) to reproduce the error

the problem comes when try to put <Text3D> from Drei as a subtraction
sandbox here: https://codesandbox.io/s/fervent-diffie-qr140c?file=/src/App.js:268-285

**Comment by samalexander** [comment]
@marcofiletto your example doesn't use this library. The [react-three-csg](https://github.com/pmndrs/react-three-csg) library you are using seems to use [three-bvh-csg](https://github.com/gkjohnson/three-bvh-csg) under the hood.
