### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'x') on CSG.intersect()

### ISSUE THREAD

**Issue by gewesp** [samalexander/three-csg-ts#61]
**Describe the bug**

caught TypeError: Cannot read properties of undefined (reading 'x')
    at NBuf3.write (NBuf.js:7:36)
    at CSG.toGeometry (CSG.js:107:28)
    at CSG.toMesh (CSG.js:156:26)
    at CSG.intersect (CSG.js:178:20)
 
**Minimal reproduction of issue**

TODO

**Expected behavior**

Gracious failure with relevant info

**Additional context**

**Comment by gewesp** [comment]
It may be related to colors.  I had one mesh with vertex coloring, the other one without.  Avoiding vertex coloring fixed it.

**Comment by samalexander** [comment]
Hi @gewesp. Please could you put together a minimal reproduction of this issue?
