### ISSUE TITLE
Transform controlls not working

### ISSUE THREAD

**Issue by imkuldeepahlawat** [samalexander/three-csg-ts#63]
refer this
https://gkjohnson.github.io/three-bvh-csg/examples/bundle/simple.html

**Comment by samalexander** [comment]
@imkuldeepahlawat please could you provide more detail.

**Comment by imkuldeepahlawat** [comment]
i havent find the example of like this , if packacge include this functionality , please add a example for that , that will be very helpful
![ezgif com-video-to-gif-converted](https://github.com/samalexander/three-csg-ts/assets/84150035/ac109116-3080-4800-96f4-c805a890b7a7)

**Comment by manthrax** [comment]
@imkuldeepahlawat

related: https://manthrax.github.io/THREE-CSGMesh/v2/index.html

and:

https://threejs.org/examples/misc_controls_transform.html
