### ISSUE TITLE
Attributes are not correct

### ISSUE THREAD

**Issue by yekiss** [samalexander/three-csg-ts#64]
![image](https://github.com/samalexander/three-csg-ts/assets/22131749/c9cf1313-c136-47e1-b49a-754e790f76fa)

There are a lots of additional lines in EdgesGeometry.

```
let geometry21 = new THREE.BoxGeometry(30, 10, 10);

const shape22 = new THREE.Shape();
shape22.absarc(0, 0, 10);
const geometry22 = new THREE.ExtrudeGeometry(shape22, extrudeSettings);
let mesh21 = new THREE.Mesh(geometry21, materialObj);
let mesh22 = new THREE.Mesh(geometry22, materialObj);
mesh21.updateMatrix();
mesh22.updateMatrix();
const result21 = CSG.subtract(mesh21, mesh22);
scene.add(result21);
let edges22 = new THREE.EdgesGeometry(result21.geometry, 10);
let line22 = new THREE.LineSegments(edges22, materialLne);
result21.add(line22);
```

**Comment by samalexander** [comment]
Hi @yekiss. Please could you provide a working reproduction of this issue via Stackblitz (or similar)? A few variables are missing from your code snippet above.

**Comment by yekiss** [comment]
> Hi @yekiss. Please could you provide a working reproduction of this issue via Stackblitz (or similar)? A few variables are missing from your code snippet above.

please check this:
https://stackblitz.com/edit/vitejs-vite-xv7phb?file=src%2FApp.vue

![Snipaste_2024-06-12_10-25-54](https://github.com/samalexander/three-csg-ts/assets/22131749/1cf9f617-9caf-40ab-a0e6-c0ffca3dc96d)
