### ISSUE TITLE
Undefined Vector

### ISSUE THREAD

**Issue by Houssk** [samalexander/three-csg-ts#7]
**Describe the bug**
First of all, thanks for this very useful asset!

I try to subtract two meshes and i have the following warning 

THREE.BufferAttribute.copyVector2sArray(): vector is undefined 

After that i have browser crach ! 
any way to fix that ?

**Comment by samalexander** [comment]
Thanks for submitting this bug report. Could you please provide steps to reproduce or a link to a StackBlitz / GitHub repo (or similar)?

**Comment by Houssk** [comment]
I have this function : 
`
update() {
    this.mortaise.position.set(
      this.sagittalCut.planification,
      0,
      this.tibialCut.planification
    );
    this.mortaise.rotation.set(
      THREE.MathUtils.degToRad(this.tibialSlope.planification),
      THREE.MathUtils.degToRad(this.varus.planification),
      THREE.MathUtils.degToRad(this.sagittalAngle.planification)
    );
    this.mortaise.updateMatrixWorld(true);
    const bspA = CSG.fromGeometry(this.geometry);
    const bspB = CSG.fromMesh(this.mortaise);
    const bspResult = bspA.subtract(bspB);
    const meshResult = CSG.toMesh(bspResult, this.mesh.matrix);
    meshResult.geometry.mergeVertices();
    console.log(meshResult);
    this.mesh.geometry = new THREE.BufferGeometry().fromGeometry(meshResult.geometry)
  }`

 when i try to affect the result mesh (geometry) i have the issue

**Comment by Houssk** [comment]
> I have this function :
> 
``` 
update() { 
this.mortaise.position.set( this.sagittalCut.planification, 0, this.tibialCut.planification ); this.mortaise.rotation.set( THREE.MathUtils.degToRad(this.tibialSlope.planification), THREE.MathUtils.degToRad(this.varus.planification), THREE.MathUtils.degToRad(this.sagittalAngle.planification) ); 
this.mortaise.updateMatrixWorld(true); 
const bspA = CSG.fromGeometry(this.geometry);
 const bspB = CSG.fromMesh(this.mortaise);
 const bspResult = bspA.subtract(bspB);
 const meshResult = CSG.toMesh(bspResult, this.mesh.matrix); meshResult.geometry.mergeVertices();
 console.log(meshResult); this.mesh.geometry = new THREE.BufferGeometry().fromGeometry(meshResult.geometry) }
```
> 
> when i try to affect the result mesh (geometry) i have the issue

this function solved my problem 👍  
```
assignUVs(geometry) {
    geometry.computeFaceNormals();
    geometry.mergeVertices();
    geometry.faceVertexUvs[0] = [];
    geometry.faces.forEach((face) => {
      // @ts-ignore
      const components = ['x', 'y', 'z'].sort((a, b) => {
        return Math.abs(face.normal[a]) > Math.abs(face.normal[b]);
      });
      const v1 = geometry.vertices[face.a];
      const v2 = geometry.vertices[face.b];
      const v3 = geometry.vertices[face.c];
      geometry.faceVertexUvs[0].push([
        new THREE.Vector2(v1[components[0]], v1[components[1]]),
        new THREE.Vector2(v2[components[0]], v2[components[1]]),
        new THREE.Vector2(v3[components[0]], v3[components[1]])
      ]);
    });
    geometry.uvsNeedUpdate = true;
    return geometry;
  }
```

**Comment by samalexander** [comment]
Unfortunately that doesn't give me enough to go on. I have a working example of mesh subtraction [here](https://stackblitz.com/edit/typescript-b72zbm). If you are able to fork and update to reproduce your issue, I will take a look.
