### ISSUE TITLE
Low transpile target makes library unusable

### ISSUE THREAD

**Issue by nikola-modelon** [samalexander/three-csg-ts#9]
**Describe the bug**
Library cannot be used with modern clients. This due to that the transpile target is too low where invoking a class constructor without "new" is not allowed.
See this explanation: https://stackoverflow.com/a/51860850

**To Reproduce**
Try to run `CSG.fromGeometry` and notice issue: https://codesandbox.io/s/priceless-chebyshev-iej5y?file=/src/index.js.
Error is thrown `Class constructor Vector3 cannot be invoked without 'new'`
_(running on Chrome Version 87.0.4280.88)_

**Expected behavior**
Library should be working in modern environments.

**Additional context**
I would suggest to transpile the library to a modern target (such as ES6), or follow steps described here: https://stackoverflow.com/a/51860850.

Please consider fixing this as it is unusable in it's current state 🙏 
Thanks!

**Comment by weiserhei** [comment]
Im also stuck on this Error since three.js `r120`. The build will throw this error and render nothing, where `r119` and previous will work.

edit:  ~119~ ->120

**Comment by nikola-modelon** [comment]
> Im also stuck on this Error since three.js `r119`. The build will throw this error and render nothing, where `r118` and previous will work.

For me when trying it out it breaks first at r120 while r119 seems to work fine. 

According to the r120 release notes, they moved a lot of entities to ES6 classes. So that is most likely why it doesn't work since the: https://github.com/mrdoob/three.js/releases/tag/r120

**Comment by altavir** [comment]
I got the same problems with usage from Kotlin-JS. I would really appreciate a fix.

**Comment by samalexander** [comment]
This is resolved in [v2.0.0](https://github.com/Jiro-Digital/three-csg-ts/releases/tag/v2.0.0)

**Comment by nikola-modelon** [comment]
> This is resolved in [v2.0.0](https://github.com/Jiro-Digital/three-csg-ts/releases/tag/v2.0.0)

Seems to work fine 👏 Thanks for fast fix and release.
